export {
  defaultOption,
  changeQuantity,
  generateKey,
  generateTotal,
  removeURLParams,
  getCountryData,
  generateCartDescription,
  getToday,
  getFutureDate,
  dateParse,
  minBookDate,
  renderEmptyDiv,
  getDayName,
  dayAndDate,
  generateClassList,
  generateClassName,
  getDuration,
  handleDisplayCapacity,
  generateDateRangeQuery,
} from "./utils";
export { componentResolver } from "./resolve";
